### ISSUE TITLE
cookie notification

### ISSUE THREAD

**Issue by behackl** [Felfio/AAUFood#10]
by the EU cookie law we are required to give some sort of notice that this site is using cookies in order to count the visitors.

**Comment by phylib** [comment]
My suggestion would be:
`Um die Anzahl der Besucher zählen zu können werden Cookies verwendet, es werden jedoch keine Daten an Dritte weitergegeben.`
- Reason first

Opinions?

**Comment by Kruemelkatze** [comment]
@mrukas suggested [https://silktide.com/tools/cookie-consent/](https://silktide.com/tools/cookie-consent/)

**Comment by phylib** [comment]
looks good for me.I  would recommend including the sources and process them with webpack instead of using the precompiled version, as recommended on the homepage.

see [github-project](https://github.com/insites/cookieconsent)

**Comment by behackl** [comment]
@phylib I'm in favor of moving "cookies" as much to the beginning of the sentence as possible (such that it still sounds okay). A text that would be a bit simpler than yours is

`Wir verwenden Cookies um Besucher dieser Website zu zählen. Gesammelte Daten werden nicht weitergegeben.`

also, https://www.youtube.com/watch?v=X_-vEsfRuHU (or something similar) should be included somehow. :smile:

**Comment by mrukas** [comment]
As @phylib suggested, including that file with webpack is a good idea. With that way the library would also be included in the final bundle. I will have a look at this.
