### ISSUE TITLE
Edge case leads to wrong price at UniWirt

### ISSUE THREAD

**Issue by fafeichter** [Felfio/AAUFood#106]
Rösti Love Burger is too expensive. ^^ Just to inform you.

parsed:
<img width="570" alt="Screenshot 2023-02-02 at 12 51 23" src="https://user-images.githubusercontent.com/13705908/216317347-ed6ddcf1-f103-452f-983f-2e3653221754.png">

original:
<img width="300" alt="Screenshot 2023-02-02 at 12 49 01" src="https://user-images.githubusercontent.com/13705908/216316940-34d47f7b-b841-46a6-ba5b-9f6bd973540a.png">

**Comment by Kruemelkatze** [comment]
Haha, will fix :D
