### ISSUE TITLE
no food section @ IE

### ISSUE THREAD

**Issue by behackl** [Felfio/AAUFood#32]
menus are not shown when using IE 11, probably because of lacking support for ecmascript6.

what can be done?

**Comment by mrukas** [comment]
The easiest way is to use Babel.js to transpile the es6 code to es5. We would have to use babel.js as loader in webpack.

[https://babeljs.io/docs/setup/#installation](https://babeljs.io/docs/setup/#installation)

**Comment by Kruemelkatze** [comment]
Done and working @ IE11.
Can someone confirm this? 💃
