### ISSUE TITLE
Printable view

### ISSUE THREAD

**Issue by Kruemelkatze** [Felfio/AAUFood#33]
An additional view which is suited for printing. Such as
[this](http://www.lakeside-scitec.com/fileadmin/user_upload/Menueplaene/Mittagstisch_Menueplan_17_KW05.pdf)

Just an idea. :)

**Comment by behackl** [comment]
Sounds good! For printing, a view showing the entire week is IMHO most suitable.

**Comment by Kruemelkatze** [comment]
Integrated with today's merge.
