### ISSUE TITLE
links to banners etc.

### ISSUE THREAD

**Issue by behackl** [Felfio/AAUFood#35]
they should be reachable from somewhere within the app, IMHO. of course, open for discussion!

**Comment by phylib** [comment]
we should not forget the posters of Krissis colleague. (one is still missing)

**Comment by behackl** [comment]
yes, i particularly meant those!

**Comment by Kruemelkatze** [comment]
Fixed by #68.

Concerning Posters: We never got them (afaik), but we have our awesome stickers. :)
