### ISSUE TITLE
Replace `setErrorOnEmpty`, `invalidateMenus` and  `sanitizeName` through methods from scraper-helper.js 

### ISSUE THREAD

**Issue by phylib** [Felfio/AAUFood#37]
from la-pasta branch.

**Comment by behackl** [comment]
Man kann beim Scraper einiges vereinheitlichen; das hier angeführte Refactoring wird vermutlich (unter Anderem) im Zuge von #44 passieren.

**Comment by Kruemelkatze** [comment]
Fixed by #68.
