### ISSUE TITLE
improve handling of docker

### ISSUE THREAD

**Issue by behackl** [Felfio/AAUFood#40]
- create a makefile for the easier use of docker
- take all other improvements from the development-branch (code volume for live updates etc.)

makefile targets:
- `run` -- starts the containers in foreground
- `run-daemon` -- runs the containers as a daemon
- `stop` -- stops the containers
- `build-css` -- runs `npm run build` in a running container
- `ssh-node` -- ssh into node container
- `ssh-redis` -- ssh into redis container

any other wishes for makefile targets?

**Comment by behackl** [comment]
maybe we should also check whether `FOOD_PORT` is set---and if not, set it to some default (e.g. 3000).

**Comment by Kruemelkatze** [comment]
Done with #41 .
