### ISSUE TITLE
route: /city

### ISSUE THREAD

**Issue by behackl** [Felfio/AAUFood#44]
Letztens mit @phylib diskutiert: es würde nicht sehr viel fehlen, um manche Menüs (la pasta, princz, ???) aus der Stadt zu parsen; es gibt sogar branches wo das schon passiert.

**Comment by behackl** [comment]
Mein Vorschlag wäre, das als nächstes Projekt für den development-branch vorzusehen. Über die genaue Abwicklung können wir aber natürlich diskutieren. :smile:

**Comment by phylib** [comment]
in meinem Branch hab ich schon eine Route ala /city/ drinnen... Wir sollten unsere 2 branches echt einmal mergen...

**Comment by behackl** [comment]
Gut, Update: eine erster Teil wurde jetzt via #47 erschlagen und die Route angelegt.

Für die Zukunft sind noch zu erledigen:

- Bastle den Branch mit pdf-parsing von princz noch dazu,
- Footer-pun für `/city`,
- und in der Sitemap würd ich es auch gern eingetragen haben

**Comment by phylib** [comment]
Was haltets von "We're going to the city [fa-building-o]"? Als footerpun...

**Comment by Kruemelkatze** [comment]
Nachdem mehr als zwei Jahre lang nichts entschieden wurde und eine zweite Seite doppelt so viel Aufwand bedeuten würde, mache ich wie angekündigt hier zu. ☠
