### ISSUE TITLE
Alignment of Footer-Elements on About-Page

### ISSUE THREAD

**Issue by phylib** [Felfio/AAUFood#45]
Position of Sitemap-Button and Visitor-Counter on About-Page is not correct. Displayed a few px's to high.

![visitor-counter](https://user-images.githubusercontent.com/2102999/30633709-f58a7cc6-9dec-11e7-91dc-fb30d8dd1dc4.PNG)

**Comment by behackl** [comment]
Eine kuriose Geschichte; irgendwas scheint mit dem Rendering nicht zu passen: Sobald sich der Counter ändert, springt das Element an die richtige Position.

**Comment by phylib** [comment]
Aber auf der Hauptseite passt alles, vermutlich handelt es sich nur um eine
Kleinigkeit :)

Am 20.09.2017 10:48 vorm. schrieb "Benjamin Hackl" <notifications@github.com

**Comment by behackl** [comment]
Hat das irgendwann mal jemand gefixed? Bei mir bringe ich das nicht mehr zusammen.

**Comment by Kruemelkatze** [comment]
Habe das wohl mit dem Redesign mitgefixt. 🤔
