### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by behackl** [Felfio/AAUFood#51]
Das Layout der AAUFood-App ist ziemlich genau auf die 4 Menüs optimiert, das ist grundsätzlich super, führt aber zum Problem, dass das Einbinden weiterer Lokale auf der Hauptseite designtechnisch nicht trivial (falls überhaupt gewünscht?) ist.

Gibt es hier Verbesserungsvorschläge, die wir einmal diskutieren* können?

(* Implementieren ist eine andere Frage.)

#50 und #23 hängen an dieser Diskussion wohl irgendwie dran. :smile:

**Comment by phylib** [comment]
Naja, bevor die Uni-Pizzeria dazu gekommen ist hats auch geheißen dass nicht mehr als 3 Lokale Platz haben. Ich glaub dass wir erst wissen dass es nicht passt, wenn wir es ausprobiert haben.

**Comment by Kruemelkatze** [comment]
Evtl. sollten wir tatsächlich mehrere Designs einfach mal ausprobieren. Z.B. wie im Mockup rechts unter die Pizzeria. Oder ein "komplett anderes" Design. Ich habe da grad leicht geneigte Post-Its statt der Bootstrap-Cards im Kopf. Die kann man dann vermutlich auch rumschieben, ohne dass es stört :)

**Comment by behackl** [comment]
Gute Idee, +1 für eine Auspro/bier/-Runde. :-)

**Comment by phylib** [comment]
Auspro/bier/-Runde klingt gut. Mein Vorschlag wäre aber: Erst im neuen Jahr? Dezember ist bei mir recht voll...

Bzgl. der Post-It Idee: Ich hab für mich als "Miniprojekt" gsetzt dass ich ein Android Widget für AAU-Food Programmier, in den Widgets kann man allerdings keine WebView Rendern. Mit native Android würden sich die Cards recht gut nachbauen lassen, Post-Its werden dann schwer... Aber gehen würds auch, es besteht die möglichkeit am Device die WebView in ein PNG umzuwandeln und das dann in einem Widget zu rendern.

**Comment by Kruemelkatze** [comment]
2 Jahre und ein Redesign später können wir das denke ich schließen. Das mit den Post-Its wurde mir damals von Dani ausgeredet, da dadurch relativ viel Platz verloren geht, man schlecht mit Farben arbeiten kann und schiefe Schrift (Post-Its müssten schief hängen, damits gut aussieht) teilweise verpixelt wirkt.

Inzwischen haben wir ja auch mehrere Lokale in einer Spalte und es passt. :)
