### ISSUE TITLE
Expired SSL certificate on food.felf.io

### ISSUE THREAD

**Issue by Laubi** [Felfio/AAUFood#77]
The website https://food.felf.io/ currently does not have a valid certificate, though it is issues by let's encrypt. Seems that the cron does not run.
Sorry for reporting the issue here, but this seems to be the best place.

![image](https://user-images.githubusercontent.com/3740651/108682688-e81b2c00-74f0-11eb-8e12-39ddce7cbf12.png)
![image](https://user-images.githubusercontent.com/3740651/108682830-1ac52480-74f1-11eb-8ddc-874299e89bed.png)

**Comment by behackl** [comment]
Thank you for reporting, the issue should be fixed now.
