### ISSUE TITLE
visitor counter

### ISSUE THREAD

**Issue by behackl** [Felfio/AAUFood#8]
see https://food.felf.io/ -- the daily user counter either does not reset or counts rather strange.

**Comment by Kruemelkatze** [comment]
It does not reset.
@mrukas executed a command for daily reset on the Redis instance of our beloved past server. I thought it to be in the code, but apparently it isn't. So we have to execute it once manually on the new server. Ask @mrukas about it. ;)

**Comment by Kruemelkatze** [comment]
fix'd by resetting the daily counter. The trigger for starting daily reset is in the code and bound to value == 1.
