### ISSUE TITLE
Bits & Bytes scraping is not working

### ISSUE THREAD

**Issue by florianmulatz** [Felfio/AAUFood#88]
Hi Guys,

bits and bytes scraping is not working. It says that the menu has not been published the whole time. Maybe the website of the restaurant itself (not the one from lakeside-park) would suits better for scraping

[LINK](https://www.princs.com/bits-bytes/)

Cheers & Thx

**Comment by fafeichter** [comment]
They all change every few months/years. 💩 Next time we simplify it by using <iframe>. 😂

Currently maintained 👉 https://food.fabian-feichter.at/.

**Comment by phylib** [comment]
Hi @fafeichter,
thanks for fixing the issues. We would be happy to include your work when you create a pull request.
Best

**Comment by fafeichter** [comment]
https://github.com/Felfio/AAUFood/pull/103

**Comment by Kruemelkatze** [comment]
Has been deployed. Thanks for raising and fixing the issues. :)
