### ISSUE TITLE
Uniwirt scraping is not working

### ISSUE THREAD

**Issue by florianmulatz** [Felfio/AAUFood#89]
Hi Guys,

The section for UNIWIRT only shows the word "information" nothing else.

Cheers & Thx

**Comment by fafeichter** [comment]
Hi, I created a fork which currently is maintained: 👉 https://food.fabian-feichter.at/.

**Comment by fafeichter** [comment]
https://github.com/Felfio/AAUFood/pull/103

**Comment by Kruemelkatze** [comment]
Thanks for reporting and fixing. Has been merged and deployed. :)
